name: Lint and test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Set up virtual environment with uv
        run: |
          uv add git+https://github.com/Cutleast/cutleast-core-lib --editable
          uv sync

      - name: Run Ruff
        run: |
          uv run ruff check src
          uv run ruff check tests

      - name: Run Pyright
        run: |
          uv run pyright --warnings src
          uv run pyright --warnings tests

      - name: Run Pytest
        run: |
          uv run pytest